# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lroux <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/06 14:23:48 by lroux             #+#    #+#              #
#    Updated: 2019/01/09 21:04:07 by lroux            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

PROJECT	:= libpf
NAME	:= $(PROJECT).a

SRCDIR	:= srcs
OBJDIR	:= objs
INCDIR	:= incs

SRCS	:= wrappers.c handlers.c lexer.c map.c utils.c subst.c \
		   handlers/char.c handlers/int.c handlers/ptr.c \
		   handlers/oct.c handlers/hex.c handlers/bonus.c \
		   handlers/float.c

LIBS	:= libft
LIBDIR	:= ..

# Include core
include ../lib.mk

