# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lroux <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/06 14:23:48 by lroux             #+#    #+#              #
#    Updated: 2019/01/17 19:39:51 by lroux            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

PROJECT	:= libft
NAME	:= $(PROJECT).a

SRCDIR	:= srcs
OBJDIR	:= objs
INCDIR	:= incs

SRCS	:= ft_memset.c ft_bzero.c ft_memcpy.c ft_memccpy.c ft_memmove.c \
		   ft_memchr.c ft_memcmp.c ft_strlen.c ft_strdup.c ft_strndup.c \
		   ft_strcpy.c ft_strncpy.c ft_strcat.c ft_strncat.c ft_strlcat.c \
		   ft_strchr.c ft_strrchr.c ft_strstr.c ft_strnstr.c ft_strcmp.c \
		   ft_strncmp.c ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isspace.c \
		   ft_isascii.c ft_isprint.c ft_isupper.c ft_islower.c ft_toupper.c \
		   ft_tolower.c ft_atoi.c ft_memdel.c ft_strnew.c ft_strdel.c \
		   ft_strclr.c ft_striter.c ft_striteri.c ft_strmap.c ft_strmapi.c \
		   ft_strequ.c ft_strnequ.c ft_strsub.c ft_strjoin.c ft_strtrim.c \
		   ft_strsplit.c ft_calloc.c ft_realloc.c ft_itostr.c ft_utostr.c \
		   ft_strnjoin.c ft_strreset.c ft_strjoinfree.c ft_strnjoinfree.c \
		   ft_sqrt.c ft_cc.c ft_cw.c ft_strupr.c ft_strlwr.c gnl.c \
		   ft_strisdigit.c ft_strisndigit.c ft_pow.c ft_intlen.c \
		   ft_uintlen.c ft_strebrk.c ft_strtoll.c ft_mk2array.c

LIBS	:=
LIBDIR	:= ..

# Include core
include ../lib.mk

